spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:h2:mem:test
    url: jdbc:p6spy:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

shiro:
  loginUrl: /login.html
  userNativeSessionManager: true
  sessionManager:
    sessionIdUrlRewritingEnabled: false